"""AgentForge AI – Demo Data for B2B Customer Discovery workflow"""

SAMPLE_COMPANIES = [
    {
        "name": "Stripe", "domain": "stripe.com", "industry": "FinTech / Payments",
        "employee_count": 8000, "revenue_usd": 14_000_000_000, "location": "San Francisco, CA",
        "tech_stack": ["React", "Ruby", "Go", "Java", "Kafka", "AWS", "PostgreSQL"],
        "news_snippet": "Stripe launches new AI-powered fraud detection platform for enterprise.",
        "founded_year": 2010, "logo_color": "#6772e5",
        "funding_stage": "Public", "total_funding_usd": 2_200_000_000,
        "investors": ["Sequoia Capital", "Andreessen Horowitz", "General Catalyst"],
        "hq_address": "354 Oyster Point Blvd, South San Francisco, CA 94080",
        "glassdoor_rating": 4.3,
        "growth_signals": ["Hiring 500+ engineers", "3x enterprise customer growth YoY", "New AI product line launched"],
        "market_position": "leader",
    },
    {
        "name": "Notion", "domain": "notion.so", "industry": "Productivity SaaS",
        "employee_count": 600, "revenue_usd": 120_000_000, "location": "San Francisco, CA",
        "tech_stack": ["React", "TypeScript", "Node.js", "PostgreSQL", "Redis", "GCP"],
        "news_snippet": "Notion raises $275M Series C, valued at $10B. Doubles enterprise sales team.",
        "founded_year": 2016, "logo_color": "#000000",
        "funding_stage": "Series C", "total_funding_usd": 343_000_000,
        "investors": ["Index Ventures", "Coatue", "Sequoia Capital"],
        "hq_address": "2300 Harrison St, San Francisco, CA 94110",
        "glassdoor_rating": 4.5,
        "growth_signals": ["Enterprise ARR doubled", "Notion AI launched with 4M+ users", "International expansion to APAC"],
        "market_position": "challenger",
    },
    {
        "name": "Linear", "domain": "linear.app", "industry": "Dev Tools SaaS",
        "employee_count": 80, "revenue_usd": 25_000_000, "location": "San Francisco, CA",
        "tech_stack": ["React", "GraphQL", "TypeScript", "PostgreSQL", "Rust"],
        "news_snippet": "Linear raises $35M Series B. Now used by 10,000+ engineering teams globally.",
        "founded_year": 2019, "logo_color": "#5E6AD2",
        "funding_stage": "Series B", "total_funding_usd": 52_000_000,
        "investors": ["Craft Ventures", "Sequoia Capital", "Accel"],
        "hq_address": "340 Pine St, San Francisco, CA 94104",
        "glassdoor_rating": 4.8,
        "growth_signals": ["300% user growth YoY", "Enterprise tier launched Q1 2024", "SOC 2 Type II certified"],
        "market_position": "challenger",
    },
    {
        "name": "Vercel", "domain": "vercel.com", "industry": "Cloud Infrastructure",
        "employee_count": 400, "revenue_usd": 110_000_000, "location": "San Francisco, CA",
        "tech_stack": ["Next.js", "Node.js", "Go", "Rust", "AWS", "Cloudflare Edge"],
        "news_snippet": "Vercel launches v0 AI-powered UI generation. Enterprise ARR surpasses $100M.",
        "founded_year": 2015, "logo_color": "#000000",
        "funding_stage": "Series D", "total_funding_usd": 313_000_000,
        "investors": ["GV", "Accel", "CRV", "Tiger Global"],
        "hq_address": "340 Pine St Ste 2000, San Francisco, CA 94104",
        "glassdoor_rating": 4.4,
        "growth_signals": ["v0 AI attracts 500K beta users", "Enterprise plan demand 5x expectations", "Partnership with AWS Amplify"],
        "market_position": "challenger",
    },
    {
        "name": "Figma", "domain": "figma.com", "industry": "Design SaaS",
        "employee_count": 1200, "revenue_usd": 400_000_000, "location": "San Francisco, CA",
        "tech_stack": ["C++", "WebAssembly", "React", "TypeScript", "GCP", "PostgreSQL"],
        "news_snippet": "Figma launches Dev Mode and AI-assisted design features. Enterprise growth accelerates.",
        "founded_year": 2012, "logo_color": "#f24e1e",
        "funding_stage": "Series F", "total_funding_usd": 333_000_000,
        "investors": ["Kleiner Perkins", "Sequoia Capital", "Greylock"],
        "hq_address": "760 Market St, San Francisco, CA 94102",
        "glassdoor_rating": 4.6,
        "growth_signals": ["Dev Mode drives 40% enterprise upsell", "AI features in beta with 2M+ users", "APAC expansion with local teams"],
        "market_position": "leader",
    },
    {
        "name": "Airtable", "domain": "airtable.com", "industry": "No-Code / Databases",
        "employee_count": 900, "revenue_usd": 150_000_000, "location": "San Francisco, CA",
        "tech_stack": ["React", "Node.js", "Python", "MySQL", "Redis", "AWS"],
        "news_snippet": "Airtable introduces AI Cobuilder and enterprise automation features.",
        "founded_year": 2012, "logo_color": "#FCB400",
        "funding_stage": "Series F", "total_funding_usd": 1_360_000_000,
        "investors": ["CRV", "Caffeinated Capital", "Thrive Capital", "D1 Capital"],
        "hq_address": "799 Market St, San Francisco, CA 94103",
        "glassdoor_rating": 3.9,
        "growth_signals": ["AI Cobuilder drives 25% new enterprise signups", "Healthcare vertical expansion", "200+ enterprise logos added in Q4"],
        "market_position": "leader",
    },
    {
        "name": "Webflow", "domain": "webflow.com", "industry": "Web Development Tools",
        "employee_count": 700, "revenue_usd": 100_000_000, "location": "San Francisco, CA",
        "tech_stack": ["React", "Node.js", "MongoDB", "AWS", "GraphQL"],
        "news_snippet": "Webflow hits $100M ARR milestone. Launches enterprise platform with SOC2 compliance.",
        "founded_year": 2013, "logo_color": "#4353FF",
        "funding_stage": "Series C", "total_funding_usd": 333_500_000,
        "investors": ["Accel", "CapitalG", "Y Combinator"],
        "hq_address": "398 11th St, San Francisco, CA 94103",
        "glassdoor_rating": 4.2,
        "growth_signals": ["100M ARR milestone reached", "Enterprise tier 3x growth", "Localization features for global markets"],
        "market_position": "challenger",
    },
    {
        "name": "Retool", "domain": "retool.com", "industry": "Low-Code / Internal Tools",
        "employee_count": 500, "revenue_usd": 80_000_000, "location": "San Francisco, CA",
        "tech_stack": ["React", "Node.js", "TypeScript", "PostgreSQL", "Redis", "AWS"],
        "news_snippet": "Retool launches AI-powered app builder. Used by 7,000+ companies to build internal tools.",
        "founded_year": 2017, "logo_color": "#F5A623",
        "funding_stage": "Series C", "total_funding_usd": 145_000_000,
        "investors": ["Sequoia Capital", "Bedrock Capital", "Y Combinator"],
        "hq_address": "1550 Bryant St, San Francisco, CA 94103",
        "glassdoor_rating": 4.1,
        "growth_signals": ["AI app builder in GA with 1M+ generations", "Financial services vertical growth 200%", "SOC 2 + HIPAA certified"],
        "market_position": "niche",
    },
]

SAMPLE_DECISION_MAKERS = {
    "Stripe": [
        {"name": "Patrick Collison", "title": "CEO & Co-Founder", "email": "patrick@stripe.com",
         "phone": "+1-415-555-0101", "linkedin_url": "https://linkedin.com/in/patrickcollison", "confidence": 0.98},
        {"name": "John Collison", "title": "President & Co-Founder", "email": "john@stripe.com",
         "phone": "+1-415-555-0102", "linkedin_url": "https://linkedin.com/in/johncollison", "confidence": 0.97},
        {"name": "Claire Hughes Johnson", "title": "Chief Operating Officer", "email": "claire@stripe.com",
         "phone": "+1-415-555-0103", "linkedin_url": "https://linkedin.com/in/clairehughesjohnson", "confidence": 0.91},
    ],
    "Notion": [
        {"name": "Ivan Zhao", "title": "CEO & Co-Founder", "email": "ivan@notion.so",
         "phone": "+1-415-555-0201", "linkedin_url": "https://linkedin.com/in/ivanz", "confidence": 0.95},
        {"name": "Simon Last", "title": "CTO & Co-Founder", "email": "simon@notion.so",
         "phone": "+1-415-555-0202", "linkedin_url": "https://linkedin.com/in/simonlast", "confidence": 0.93},
    ],
    "Linear": [
        {"name": "Karri Saarinen", "title": "CEO & Co-Founder", "email": "karri@linear.app",
         "phone": "+1-415-555-0301", "linkedin_url": "https://linkedin.com/in/karrisaarinen", "confidence": 0.96},
        {"name": "Jori Lallo", "title": "CTO & Co-Founder", "email": "jori@linear.app",
         "phone": "+1-415-555-0302", "linkedin_url": "https://linkedin.com/in/jorilallo", "confidence": 0.94},
    ],
    "Vercel": [
        {"name": "Guillermo Rauch", "title": "CEO & Founder", "email": "rauch@vercel.com",
         "phone": "+1-415-555-0401", "linkedin_url": "https://linkedin.com/in/rauchg", "confidence": 0.97},
        {"name": "Malte Ubl", "title": "CTO", "email": "malte@vercel.com",
         "phone": "+1-415-555-0402", "linkedin_url": "https://linkedin.com/in/malteubl", "confidence": 0.89},
    ],
    "Figma": [
        {"name": "Dylan Field", "title": "CEO & Co-Founder", "email": "dylan@figma.com",
         "phone": "+1-415-555-0501", "linkedin_url": "https://linkedin.com/in/dylanfield", "confidence": 0.96},
        {"name": "Evan Wallace", "title": "CTO & Co-Founder", "email": "evan@figma.com",
         "phone": "+1-415-555-0502", "linkedin_url": "https://linkedin.com/in/evanwallace", "confidence": 0.93},
    ],
    "Airtable": [
        {"name": "Howie Liu", "title": "CEO & Co-Founder", "email": "howie@airtable.com",
         "phone": "+1-415-555-0601", "linkedin_url": "https://linkedin.com/in/howieliu", "confidence": 0.95},
        {"name": "Andrew Ofstad", "title": "CPO & Co-Founder", "email": "andrew@airtable.com",
         "phone": "+1-415-555-0602", "linkedin_url": "https://linkedin.com/in/andrewofstad", "confidence": 0.90},
    ],
    "Webflow": [
        {"name": "Vlad Magdalin", "title": "CEO & Co-Founder", "email": "vlad@webflow.com",
         "phone": "+1-415-555-0701", "linkedin_url": "https://linkedin.com/in/vladmagdalin", "confidence": 0.94},
    ],
    "Retool": [
        {"name": "David Hsu", "title": "CEO & Co-Founder", "email": "david@retool.com",
         "phone": "+1-415-555-0801", "linkedin_url": "https://linkedin.com/in/retool", "confidence": 0.93},
        {"name": "Alex Rattray", "title": "CTO & Co-Founder", "email": "alex@retool.com",
         "phone": "+1-415-555-0802", "linkedin_url": "https://linkedin.com/in/alexrattray", "confidence": 0.90},
    ],
}

ICP_CRITERIA = {
    "industry": ["SaaS", "FinTech", "Dev Tools", "Cloud Infrastructure", "Design", "No-Code"],
    "min_employees": 50,
    "max_employees": 10000,
    "min_revenue_usd": 1_000_000,
    "regions": ["North America", "Europe", "APAC"],
    "tech_requirements": ["REST API", "Cloud Infrastructure", "TypeScript", "React"],
    "funding_stages": ["Series A", "Series B", "Series C", "Series D", "Series E", "Series F", "Public"],
    "keywords": ["growth", "scale", "enterprise", "platform", "API", "developer"],
    "ideal_score_weights": {
        "industry_match": 0.30,
        "employee_count": 0.20,
        "revenue": 0.20,
        "tech_alignment": 0.15,
        "growth_signals": 0.15,
    },
}
